version: '3.4'

services:
  keepnotes:
    image: keepnotes:dev
    build:
      target: base
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_keepnotes$
    volumes:
      - E:\workspace\ASP.net\todo-mvc-csharp-problem-Preetham-D\KeepNotes:/app
      - C:\Users\Admin\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_keepnotes$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_keepnotes$ bin/Debug/netcoreapp2.1/KeepNotes.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""
